### ISSUE TITLE
Selecting generic families

### ISSUE THREAD

**Issue by dhardy** [RazrFalcon/fontdb#11]
This lib includes `fn set_serif_family` etc. but has no default assignments, which may be useful in lieu of a full `fontconfig` implementation.

Font-kit does do this, [here](https://github.com/servo/font-kit/blob/master/src/source.rs#L44).

P.S. close as "out of scope" if you like; this isn't clear from the README.

**Comment by RazrFalcon** [comment]
Yes, this is a good idea. Not sure why I've didn't do this initially.
