### ISSUE TITLE
Implement ToString or Display for font face ID

### ISSUE THREAD

**Issue by 7sDream** [RazrFalcon/fontdb#38]
I'm using fontdb with egui crate, it's [`FontDefinitions` need a string key](https://docs.rs/egui/0.20.1/egui/struct.FontDefinitions.html#structfield.font_data) to store font face data, I think the `ID` type is a prefect unique identifier for font face, but for now, because the internal `u32` is private, the only way I can convert it to a string is using the `Debug` trait(`format!("{id:?}")`). it works well, but kind of weird……

So can we add a `ToString` or `Display` impl for `ID`? With some document like: 

> We only promise that unequal IDs don't output the same string, but does not make any guarantees about the format/content of output string.

or something like this, to guarantee non-breaking changes when modifying the internal implementation.

**Comment by RazrFalcon** [comment]
Yes, adding Display is a good idea. You can send a PR or I will add it later.

**Comment by 7sDream** [comment]
OK, I can make a PR for that. 

But I need to work on other boring things for a few hours 😢, so maybe I only can finish it tomorrow.

**Comment by RazrFalcon** [comment]
No hurry. I will be able to do it myself only on the weekends anyway.
