### ISSUE TITLE
Mismatched font weight for weigths 400/500

### ISSUE THREAD

**Issue by lhinderberger** [RazrFalcon/fontdb#41]
This is a tracking issue for the bug described in #40, opened since the mentioned PR was auto-closed.

A patch on top of v0.11.2 is available at https://github.com/RazrFalcon/fontdb/pull/40#issuecomment-1409120554.

Alternatively, a refactoring/rewrite of the querying logic is being considered, for which a separate PR will be opened once it's ready.

**Comment by RazrFalcon** [comment]
Fixed via https://github.com/RazrFalcon/fontdb/commit/db3d1abb017665833244fd09d92a740e7282a2cb
