### ISSUE TITLE
Font family names are not matched according to spec

### ISSUE THREAD

**Issue by lhinderberger** [RazrFalcon/fontdb#42]
In the CSS Fonts Module Level 3 spec (see https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-family-casing), case-insensitive, folding matching of font family names is required. Currently, font family names in fontdb are matched by string equality.

For example, "FOO sans" does not match "Foo Sans" and "massanzug serif" does not match "Maßanzug Serif" (examples from query tests, see draft PR for query logic rewrite).

**Comment by RazrFalcon** [comment]
Case-insensitive matching is very expensive (Unicode one, not the ASCII one) and it's an extreme edge-case in general. Therefore it is ignored.

**Comment by lhinderberger** [comment]
If spec conformity is what we're aiming for, case-insensitive matching can't simply be ignored. But maybe we can add a flag to `Query` that optionally enables case-insensitive matching? By the way, the `unicase` crate is able to detect ASCII-only strings and only perform Unicode folding and comparison if necessary (at the cost of scanning the string for non-ASCII characters of course).

**Comment by RazrFalcon** [comment]
fontdb isn't a browser-grade library. It is good enough and I do not have plans evolving it into something bigger.

Also, `unicase` is far too heavy of a dependency for something as simple as fontdb.
