### ISSUE TITLE
Database::push_face_info does not return auto-generated ID

### ISSUE THREAD

**Issue by lhinderberger** [RazrFalcon/fontdb#44]
When adding a FaceInfo entry to the database using Database::push_face_info, the corresponding FaceInfo ID is auto-generated.
It would be useful, especially for testing, to return that auto-generated ID from push_face_info, to be able to reliably identify the newly inserted entry.

**Comment by RazrFalcon** [comment]
`load_font` methods do not return one either, so this is expected. For testing you can simply loop over faces and get the one you need.

**Comment by lhinderberger** [comment]
That's the point I'm trying to make - looping over the faces and getting the one that was just inserted is less than ideal. And if `load_font` doesn't return an ID either, maybe we should change that too?

**Comment by RazrFalcon** [comment]
`load_font` cannot return an ID, because a font collection will produce multiple IDs. And returning a `Vec<ID>` is even worse.
