### ISSUE TITLE
Find a faster dir scanning algorithm

### ISSUE THREAD

**Issue by RazrFalcon** [RazrFalcon/fontdb#5]
`std::fs::read_dir` is pretty slow and allocates a lot.

**Comment by messense** [comment]
How about using the [walkdir](https://github.com/BurntSushi/walkdir) crate?

**Comment by RazrFalcon** [comment]
Yes, I plan to test this crate.

**Comment by RazrFalcon** [comment]
`walkdir` is slightly faster, but depends on `winapi`, which is no go.
