### ISSUE TITLE
How to get a font id after I load the font?

### ISSUE THREAD

**Issue by shi-yan** [RazrFalcon/fontdb#51]
Hello there

I'm using this API to load a local font:

```rust
 .load_font_file("./font/UbuntuMono-Regular.ttf")
    .unwrap();
```

But I don't know how to get its ID, I want to check its family name etc. Does it make sense to let this function return the ID?

**Comment by RazrFalcon** [comment]
A font can have multiple IDs. Because fontdb stores faces, not fonts. To get the last added face info simply use `db.faces().last()`

**Comment by shi-yan** [comment]
Thank you very much, but do you think returning an array of IDs by this function makes sense? or maybe the family name?

What I want to achieve is a font fallback system for a terminal emulator.

I want to package this terminal emulator with a few hand-picked ttf files and use them as defaults. When these defaults can't handle certain languages, I want to rely on fontdb for finding fallbacks.

When my program starts, I load the font files and give them higher priority. But because I don't know how to find their IDs, I don't know how to refer to them.

Right now, I simply use a query to get an ID, as I know the family name of these fonts. But, say, if I want users to be able to supply their font files, I don't know how I can refer to those fonts.

**Comment by RazrFalcon** [comment]
>but do you think returning an array of IDs by this function makes sense

This would require a needless allocation or an additional dependency like `tinyvec`.

As for your issue, can't you simply load your fonts first, remember their IDs and only then load systems fonts?

Also, family name doesn't guarantee to be uniques, so this is not an option. The only unique thing in fontdb is `fontdb::ID`.

**Comment by shi-yan** [comment]
Oh, I see what you mean, thank you.

Somehow, my code loads system fonts even without me calling load_system_fonts(). So I thought fontdb loaded everything automatically. I'm not using fontdb directly, I'm using a wrapper code. Maybe it is the wrapper that loads the system fonts first. I will double-check. Thanks!
