### ISSUE TITLE
consider enabling `fontconfig` feature by default

### ISSUE THREAD

**Issue by urlordjames** [RazrFalcon/fontdb#56]
I think it's worth considering enabling the `fontconfig` feature be enabled by default.  Without the `fontconfig` feature enabled, `fontdb` is unable to discover system fonts on NixOS (#20).  Enabling the `fontconfig` feature by default would make dependents easier to work with on NixOS, and would prevent opening an issue to enable the feature for each dependent that wishes to support NixOS (see pop-os/cosmic-text#167).

As an alternative to enabling the `fontconfig` feature by default, a note could be added to `README.md` to inform users that enabling the feature is more portable.

Any thoughts on this?

**Comment by RazrFalcon** [comment]
The current `fontconfig` support isn't perfect, therefore it isn't enabled by default.
I'm not sure what would be the right move here. If it required by NixOS, then I guess we should comply with "sane defaults". But the non-fontconfig version should typically be better/faster on normal distros. 

I will think about it.

PS: I'm not sure how cross-platform `cosmic-text` is, but a proper Linux solution would require using `fontconfig` directly, avoiding `fontdb` entirely.
