### ISSUE TITLE
linux fontconfig: wrong handling of <include> directives

### ISSUE THREAD

**Issue by MHellmund** [RazrFalcon/fontdb#59]
(Typst user here, no experience with Rust)

[Typst](https://github.com/typst/typst) 0.9  uses now fontdb, but still doesn't find all the fonts on my linux box. 

`strace -f typst fonts`   

```
openat(AT_FDCWD, "/etc/fonts/fonts.conf", O_RDONLY|O_CLOEXEC) = 3
statx(3, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2940, ...}) = 0
read(3, "<?xml version=\"1.0\"?>\n<!DOCTYPE "..., 2940) = 2940
read(3, "", 32)                         = 0
close(3)                                = 0
statx(AT_FDCWD, "conf.d", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7fff2d98bb80) = -1 ENOENT (No such file or directory)
```

```
#ls /etc/fonts/conf.d/
10-hinting-slight.conf
10-scale-bitmap-fonts.conf
10-yes-antialias.conf
11-lcdfilter-default.conf
20-unhint-small-dejavu-lgc-sans-mono.conf
20-unhint-small-dejavu-lgc-sans.conf
20-unhint-small-dejavu-lgc-serif.conf
20-unhint-small-dejavu-sans-mono.conf
20-unhint-small-dejavu-sans.conf
...
```

It seems to me that the 
```
   <include ignore_missing="yes">conf.d</include>
```
line of `/etc/fonts/fonts.conf`  is not interpreted  in the right way, i.e., relative to the dir where `fonts.conf` is. 

The same happens with `$HOME/.config/fontconfig/{fonts.conf,conf.d/}

**Comment by RazrFalcon** [comment]
fontconfig isn't supported and not planned. `fontdb` does support some basic stuff, but it should not be relied on. 
A proper fontconfig support is out of the scope of this crate.

**Comment by MHellmund** [comment]
Please correct me, but shouldn't `fontdb`  at least find all the font paths?  E.g., Nix/home-manager generates a file `$HOME/ .config/fontconfig/conf.d/10-hm-fonts.conf` with directives like 
`  <dir>/nix/store/y8jl2nqkxdydwihbspadcwhgf6k5zvc7-home-manager-path/share/fonts</dir>`

**Comment by RazrFalcon** [comment]
That's a Nix problem, not fontdb one. The current implementation is fine for most Linux distros.
Therefore unless someone using Nix would send a patch this would never be supported.

**Comment by PgBiel** [comment]
> line of `/etc/fonts/fonts.conf` is not interpreted in the right way, i.e., relative to the dir where `fonts.conf` is.

I believe this would be an issue to be raised with [upstream `fontconfig_parser`](https://github.com/Riey/fontconfig-parser). Crafting a minimal Rust program using `fontconfig_parser` in an attempt to reproduce this would be ideal before reporting the issue upstream.

Relevant parts of upstream code:

https://github.com/Riey/fontconfig-parser/blob/e9d723acbf72dd34eb15495049aba72f8d5376ed/src/types/dir.rs#L93

https://github.com/Riey/fontconfig-parser/blob/e9d723acbf72dd34eb15495049aba72f8d5376ed/src/types/document.rs#L62

https://github.com/Riey/fontconfig-parser/blob/e9d723acbf72dd34eb15495049aba72f8d5376ed/src/types/document.rs#L81

I don't see obvious problems in the upstream code in principle, but might be interesting to ask there anyway.

A quick solution is to use absolute paths for `include` in fontconfig configuration files instead if possible.

**Comment by PgBiel** [comment]
Actually, **this behavior is correct.** I've verified the spec at https://www.freedesktop.org/software/fontconfig/fontconfig-user.html, and you need to **explicitly opt into using the conf file's path as a base** (instead of the reading program's CWD) by specifying the `prefix` attribute as `relative`:

```xml
<include prefix="relative">conf.d</include>
```

Therefore, `fontconfig_parser` is simply following the spec here, and this issue should likely be closed.

**Comment by PgBiel** [comment]
As an aside, I believe the issue with `10-hm-fonts.conf` might be that (at least from my interpretation of the `fontdb` code, so sorry if I get this wrong) the `conf.d` directories aren't checked by default, and you'll need to manually add a `fonts.conf` pointing to the correct `conf.d` directory. It could be nice for `fontdb` to automatically check those directories, but whether or not that is worth it is a separate discussion, and totally orthogonal to this particular issue.

**Comment by RazrFalcon** [comment]
@PgBiel I'm not using Linux and have no idea how fontconfig works. Its support is out of scope of this crate.
Ideally, someone should write a good fontconfig crate, which then can be used from fontdb.

**Comment by PgBiel** [comment]
> @PgBiel I'm not using Linux and have no idea how fontconfig works. Its support is out of scope of this crate.

Oh, of course; I was speaking mostly from a perspective of finding as many system fonts as possible (since some Linux distributions depend on fontconfig for system fonts). Fontconfig, as I see it, has a good chunk of other features which are way out of scope for `fontdb`. But I believe this matter of analyzing more directories could be discussed in another issue if proven necessary (and if we have more data) - the current implementation is already _much_ better than just not detecting anything from fontconfig.

> Ideally, someone should write a good fontconfig crate, which then can be used from fontdb.

No doubt. It seems that the strongest contender for that, so far, is the [`fontconfig` crate](https://lib.rs/crates/fontconfig), but it doesn't seem to be pure Rust, and I'm not sure how feature-complete it is.

**Comment by MHellmund** [comment]
> Actually, **this behavior is correct.** I've verified the spec at https://www.freedesktop.org/software/fontconfig/fontconfig-user.html, and you need to **explicitly opt into using the conf file's path as a base** (instead of the reading program's CWD) by specifying the `prefix` attribute as `relative`:
...
> 
> Therefore, `fontconfig_parser` is simply following the spec here, and this issue should likely be closed.

You are right. Sorry for the noise.

**Comment by MHellmund** [comment]
Not a bug.

**Comment by RazrFalcon** [comment]
>It seems that the strongest contender for that, so far, is the [fontconfig crate](https://lib.rs/crates/fontconfig)

This crate is just a bindings to fontconfig, which this library tries to avoid. Calling fontconfig is very slow (last time I've checked) and it doesn't have as low-level access to fonts metadata as we need.

In fontdb I need a pure Rust fontconfig configuration parser. I don't really need anything else. 
The problem that config files are poorly documented and it would take a lot of work to write a good implementation.
