### ISSUE TITLE
load_system_fonts() shouldn't load blacklisted `<rejectfont>` fonts

### ISSUE THREAD

**Issue by munzirtaha** [RazrFalcon/fontdb#70]
First and foremost, thank you for your wonderful projects. I am here because `Typst` loaded my blacklisted fonts 
typst/typst#4848

Font configuration files of `fontconfig` in Linux use this syntax to load fonts from a specific location and blacklist others.

```
<dir>/usr/share/fonts</dir>
<rejectfont><glob>/usr/share/fonts/TTF/*Thai*</glob></rejectfont>
```

What's the proper way to handle this?

**Comment by RazrFalcon** [comment]
`fontconfig` isn't supported and not planned.

**Comment by munzirtaha** [comment]
Thanks for clarifying the situation.

**Comment by munzirtaha** [comment]
.
